version: '2'

services:
  libresonic:
    image: wonderfall/libresonic
    container_name: libresonic
    volumes:
    - ${DATA_ROOT}/libresonic/data:/data
    - ${DATA_ROOT}/libresonic/musics:/musics
  nginx:
    image: wonderfall/boring-nginx
    container_name: nginx
    links:
    - libresonic
    ports:
    - "80:8000"
    - "443:4430"
    volumes:
    - ${DATA_ROOT}/nginx/sites-enabled:/sites-enabled
    - ${DATA_ROOT}/nginx/conf:/conf.d
    - ${DATA_ROOT}/nginx/log:/var/log/nginx
    - ${DATA_ROOT}/nginx/certs:/certs
